### PR TITLE
Fix grammar, ADSR image and WinXound link @ Get started page

### PR DESCRIPTION
**Pull request by iver56**
* Fix some grammar
* Fix ADSR image (it didn't show up in the post)
* Fix WinXound link

### CODE REVIEW

**Comment by jpffitch** [comment]
Either spelling is accepted in Csound

⁣

Sent from TypeApp

​

**Comment by iver56** [comment]
I see. Which one is preferred though?

For reference, I googled both:
"Synthesiser": 976 000 hits
"Synthesizer": 24 100 000 hits

**Comment by vlazzarini** [comment]
For whatit's worth, I use synthesiser.

**Comment by iver56** [comment]
That's quite alright. I undid my change from synthesizer to synthesiser 😄

**Comment by vlazzarini** [comment]
thanks for your contribution

**Comment by jpffitch** [comment]
American v English is suspect

**Pull request merged**
